service: elasticbeanstalk-slack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  memorySize: 128
  timeout: 4
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'kms:Decrypt'
      Resource:
        - ${env:KMS_KEY_ARN}

package:
  exclude:
    - node_modules/**

functions:
  handler:
    handler: handler.handler
    environment:
      kmsEncryptedHookUrl: ${env:WEBHOOK_URL}
      slackChannel: ${env:SLACK_CHANNEL}
    events:
      - sns: ${env:SNS_ARN}
