service:
  name: step-functions-slack

plugins:
  - serverless-webpack

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs8.10
  memorySize: 128
  timeout: 8

functions:
  handler:
    handler: handler.handler
    environment:
      SLACK_WEBHOOK_PATH: ${env:SLACK_WEBHOOK_PATH}
    events:
      - sns: ${env:SNS_ARN}
