name: Python
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: elasticache
      run: |
        python -m pip install --upgrade pip
        cd elasticache
        pip install -r requirements.txt
        pip install pylint
        pylint handler.py
